from rows import USLegislationRow

row = USLegislationRow(goverlytics_id='WA_20212022_1001',
                       source_id='',
                       bill_name='1001',
                       session='2021-22',
                       date_introduced='2021-01-11',
                       source_url='http://lawfilesext.leg.wa.gov/biennium/2021-22/Htm/Bills/House Bills/1001.htm',
                       chamber_origin='House',
                       committees=[{'chamber': 'House', 'committee': 'House Appropriations'},
                                   {'chamber': 'Senate',
                                       'committee': 'Senate Law & Justice'},
                                   {'chamber': 'Senate', 'committee': 'Senate Ways & Means'}],
                       bill_type='Bill',
                       bill_title='AN ACT Relating to establishing a law enforcement professional development outreach grant program;',
                       current_status='Effective date 7/25/2021.',
                       principal_sponsor_id=52953,
                       principal_sponsor='Jacquelin Maycumber',
                       sponsors=['Maycumber', 'Lovick', 'Ryu', 'Boehnke', 'Leavitt', 'Lekanoff',
                                 'Tharinger', 'Goodman', 'Young', 'Graham', 'Cody', 'Robertson', 'Johnson'],
                       sponsors_id=[52953, 52950, 52971, 52906, 52948, 52949,
                                    52987, 52930, 52997, 52931, 52915, 52968, 52941],
                       cosponsors=[],
                       cosponsors_id=[],
                       bill_text='',
                       bill_description='Establishing a law enforcement professional development outreach grant program.',
                       bill_summary='',
                       actions=[{'date': '2021-01-11', 'description': 'First reading, referred to Appropriations.', 'action_by': 'chamber'},
                                {'date': '2021-02-04', 'description': 'APP - Executive action taken by committee.',
                                 'action_by': 'committee'},
                                {'date': '2021-02-04', 'description': 'APP - Majority; do pass.',
                                 'action_by': 'chamber'},
                                {'date': '2021-02-09', 'description': 'Referred to Rules 2 Review.',
                                 'action_by': 'chamber'},
                                {'date': '2021-02-09', 'description': 'Placed on second reading by Rules Committee.',
                                 'action_by': 'chamber'},
                                {'date': '2021-02-10', 'description': 'Rules suspended.  Placed on Third Reading.',
                                 'action_by': 'chamber'},
                                {'date': '2021-02-10', 'description': 'Third reading, passed; yeas, 98; nays, 0; absent, 0; excused, 0.',
                                 'action_by': 'chamber'},
                                {'date': '2021-02-12', 'description': 'First reading, referred to Law & Justice.',
                                 'action_by': 'chamber'},
                                {'date': '2021-03-04', 'description': 'LAW - Majority; do pass.',
                                 'action_by': 'chamber'},
                                {'date': '2021-03-04', 'description': 'And refer to Ways & Means.',
                                 'action_by': 'chamber'},
                                {'date': '2021-03-05', 'description': 'Referred to Ways & Means.',
                                 'action_by': 'chamber'},
                                {'date': '2021-03-22', 'description': 'WM - Majority; do pass.',
                                 'action_by': 'chamber'},
                                {'date': '2021-03-23', 'description': 'Passed to Rules Committee for second reading.',
                                 'action_by': 'chamber'},
                                {'date': '2021-03-26', 'description': 'Placed on second reading by Rules Committee.',
                                 'action_by': 'chamber'},
                                {'date': '2021-04-06', 'description': 'Rules suspended.  Placed on Third Reading.',
                                 'action_by': 'chamber'},
                                {'date': '2021-04-06', 'description': 'Third reading, passed; yeas, 49; nays, 0; absent, 0; excused, 0.',
                                 'action_by': 'chamber'},
                                {'date': '2021-04-07', 'description': 'Speaker signed.',
                                 'action_by': 'speaker'},
                                {'date': '2021-04-09', 'description': 'President signed.',
                                 'action_by': 'president'},
                                {'date': '2021-04-13', 'description': 'Delivered to Governor.',
                                 'action_by': 'governor'},
                                {'date': '2021-04-16', 'description': 'Governor signed.',
                                 'action_by': 'governor'},
                                {'date': '2021-04-16', 'description': 'Chapter 52, 2021 Laws.',
                                 'action_by': 'secretary of state'},
                                {'date': '2021-04-16', 'description': 'Effective date 7/25/2021.', 'action_by': 'secretary of state'}],
                       votes=[{'date': '2021-04-06', 'description': '3rd Reading & Final Passage', 'yea': 49, 'nay': 0, 'nv': 0, 'absent': 0, 'total': 49, 'passed': 1, 'chamber': 'Senate',
                               'votes': [{'goverlytics_id': 52998, 'legislator': 'Billig', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52999,
                                          'legislator': 'Braun', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53000,
                                          'legislator': 'Brown', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53001,
                                          'legislator': 'Carlyle', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53002,
                                          'legislator': 'Cleveland', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53003,
                                          'legislator': 'Conway', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53004,
                                          'legislator': 'Darneille', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53005,
                                          'legislator': 'Das', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53006,
                                          'legislator': 'Dhingra', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53007,
                                          'legislator': 'Dozier', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53008,
                                          'legislator': 'Ericksen', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53009,
                                          'legislator': 'Fortunato', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53010,
                                          'legislator': 'Frockt', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53011,
                                          'legislator': 'Gildon', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53012,
                                          'legislator': 'Hasegawa', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53013,
                                          'legislator': 'Hawkins', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53014,
                                          'legislator': 'Hobbs', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53015,
                                          'legislator': 'Holy', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53016,
                                          'legislator': 'Honeyford', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53017,
                                          'legislator': 'Hunt', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53018,
                                          'legislator': 'Keiser', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53019,
                                          'legislator': 'King', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53020,
                                          'legislator': 'Kuderer', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53021,
                                          'legislator': 'Liias', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53022,
                                          'legislator': 'Lovelett', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53023,
                                          'legislator': 'McCune', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53024,
                                          'legislator': 'Mullet', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53025,
                                          'legislator': 'Muzzall', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53026,
                                          'legislator': 'Nguyen', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53027,
                                          'legislator': 'Nobles', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53028,
                                          'legislator': 'Padden', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53029,
                                          'legislator': 'Pedersen', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53030,
                                          'legislator': 'Randall', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53031,
                                          'legislator': 'Rivers', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53032,
                                          'legislator': 'Robinson', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53033,
                                          'legislator': 'Rolfes', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53034,
                                          'legislator': 'Saldaña', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53035,
                                          'legislator': 'Salomon', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53036,
                                          'legislator': 'Schoesler', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53037,
                                          'legislator': 'Sheldon', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53038,
                                          'legislator': 'Short', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53039,
                                          'legislator': 'Stanford', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53040,
                                          'legislator': 'Van De Wege', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53041,
                                          'legislator': 'Wagoner', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53042,
                                          'legislator': 'Warnick', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53043,
                                          'legislator': 'Wellman', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53044,
                                          'legislator': 'Wilson, C.', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53045,
                                          'legislator': 'Wilson, J.', 'votetext': 'Yea'},
                                         {'goverlytics_id': 53046, 'legislator': 'Wilson, L.', 'votetext': 'Yea'}]},
                              {'date': '2021-02-10', 'description': '3rd Reading & Final Passage', 'yea': 98, 'nay': 0, 'nv': 0, 'absent': 0, 'total': 98, 'passed': 1, 'chamber': 'House',
                               'votes': [{'goverlytics_id': 52900, 'legislator': 'Abbarno', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52901,
                                          'legislator': 'Barkis', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52902,
                                          'legislator': 'Bateman', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52903,
                                          'legislator': 'Berg', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52904,
                                          'legislator': 'Bergquist', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52905,
                                          'legislator': 'Berry', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52906,
                                          'legislator': 'Boehnke', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52907,
                                          'legislator': 'Bronoske', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52908,
                                          'legislator': 'Caldier', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52909,
                                          'legislator': 'Callan', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52910,
                                          'legislator': 'Chambers', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52911,
                                          'legislator': 'Chandler', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52912,
                                          'legislator': 'Chapman', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52913,
                                          'legislator': 'Chase', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52914,
                                          'legislator': 'Chopp', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52915,
                                          'legislator': 'Cody', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52916,
                                          'legislator': 'Corry', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52917,
                                          'legislator': 'Davis', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52918,
                                          'legislator': 'Dent', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52919,
                                          'legislator': 'Dolan', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52920,
                                          'legislator': 'Duerr', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52921,
                                          'legislator': 'Dufault', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52922,
                                          'legislator': 'Dye', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52923,
                                          'legislator': 'Entenman', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52924,
                                          'legislator': 'Eslick', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52925,
                                          'legislator': 'Fey', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52926,
                                          'legislator': 'Fitzgibbon', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52927,
                                          'legislator': 'Frame', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52928,
                                          'legislator': 'Gilday', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52929,
                                          'legislator': 'Goehner', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52930,
                                          'legislator': 'Goodman', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52931,
                                          'legislator': 'Graham', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52932,
                                          'legislator': 'Gregerson', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52933,
                                          'legislator': 'Griffey', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52934,
                                          'legislator': 'Hackney', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52935,
                                          'legislator': 'Hansen', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52945,
                                          'legislator': 'Kloba', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52946,
                                          'legislator': 'Kraft', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52947,
                                          'legislator': 'Kretz', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52948,
                                          'legislator': 'Leavitt', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52949,
                                          'legislator': 'Lekanoff', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52950,
                                          'legislator': 'Lovick', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52951,
                                          'legislator': 'MacEwen', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52952,
                                          'legislator': 'Macri', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52953,
                                          'legislator': 'Maycumber', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52954,
                                          'legislator': 'McCaslin', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52955,
                                          'legislator': 'McEntire', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52956,
                                          'legislator': 'Morgan', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52957,
                                          'legislator': 'Mosbrucker', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52958,
                                          'legislator': 'Orcutt', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52959,
                                          'legislator': 'Ormsby', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52960,
                                          'legislator': 'Ortiz-Self', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52961,
                                          'legislator': 'Orwall', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52962,
                                          'legislator': 'Paul', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52963,
                                          'legislator': 'Peterson', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52964,
                                          'legislator': 'Pollet', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52965,
                                          'legislator': 'Ramel', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52966,
                                          'legislator': 'Ramos', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52967,
                                          'legislator': 'Riccelli', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52968,
                                          'legislator': 'Robertson', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52969,
                                          'legislator': 'Rude', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52970,
                                          'legislator': 'Rule', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52971,
                                          'legislator': 'Ryu', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52972,
                                          'legislator': 'Santos', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52973,
                                          'legislator': 'Schmick', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52974,
                                          'legislator': 'Sells', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52975,
                                          'legislator': 'Senn', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52976,
                                          'legislator': 'Shewmake', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52977,
                                          'legislator': 'Simmons', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52978,
                                          'legislator': 'Slatter', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52979,
                                          'legislator': 'Springer', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52980,
                                          'legislator': 'Steele', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52981,
                                          'legislator': 'Stokesbary', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52982,
                                          'legislator': 'Stonier', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52983,
                                          'legislator': 'Sullivan', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52984,
                                          'legislator': 'Sutherland', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52985,
                                          'legislator': 'Taylor', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52986,
                                          'legislator': 'Thai', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52987,
                                          'legislator': 'Tharinger', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52988,
                                          'legislator': 'Valdez', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52989,
                                          'legislator': 'Vick', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52990,
                                          'legislator': 'Volz', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52991,
                                          'legislator': 'Walen', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52992,
                                          'legislator': 'Walsh', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52993,
                                          'legislator': 'Wicks', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52994,
                                          'legislator': 'Wilcox', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52995,
                                          'legislator': 'Wylie', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52996,
                                          'legislator': 'Ybarra', 'votetext': 'Yea'},
                                         {'goverlytics_id': 52997, 'legislator': 'Young', 'votetext': 'Yea'}]}],
                       source_topic='',
                       topic='',
                       country_id=1,
                       country='United States of America',
                       state_id=53,
                       state='WA')
