name: ca_provincial scrapers

on:
#   schedule:
#     - cron: "*/5 * * * *"
  push:
      branches:
        - main
    
jobs:
  build:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
    steps:       
      - name: setup chrome
        uses: browser-actions/setup-chrome@latest
        
      - name: download chrome
        run: chrome --version
        with: 
          chrome-version: latest
          
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
        
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2
        
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_RDS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_RDS_SECRET_ACCESS_KEY }}
        
      - name: Allow Security group rule to connect Github Actions to PostgresSQL
        run: |
          aws ec2 authorize-security-group-ingress --group-name openparlPermittedIPAddresses --protocol tcp --port 5432 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # install the python version needed
        
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
          
      - name: execute py script 
        run: |
          $file = Get-ChildItem -Path scrapers\ca\ca-provinces -Recurse *bc_legislator_scraper.py
          python $file
          
      - name: Deny Security group rule to connect Github Actions to PostgresSQL
        run: |
          aws ec2 revoke-security-group-ingress --group-name openparlPermittedIPAddresses --protocol tcp --port 5432 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        if: always()
